Restructure repo by introducing account creation and authorization in…
Sitelink3D-v2-Developer/sitelink3dv2-api-documentation pull request #6
Opened 2021-11-24 05:38 UTC by yeleva

…formation, technical overview and security walk-through all initially hosted on the TSDN.

2021-12-10 05:15 UTC, Ryan-A-B commented on security/security_overview.md
> +One can perhaps start to imagine some of the problems that rapidly arise from this approach. Because Giant Bank is required to authenticate the identities of users of its services, it necessarily nee
```suggestion
One can perhaps start to imagine some of the problems that rapidly arise from this approach. Because Giant Bank is required to authenticate the identities of users of its services, it necessarily needs to know about all the customers of all the banks that it on-sells to. Privacy issues aside, the mechanics of this become unmanageable.
```

2021-12-10 05:15 UTC, Ryan-A-B commented on security/security_overview.md
> +Already we have presented enough information to make some sense of the Sitelink3D v2 REST API defined on our [Swagger](https://api.sitelink.topcon.com/swagger/) page. Security tokens are provided to
```suggestion
Already we have presented enough information to make some sense of the Sitelink3D v2 REST API defined on our [Swagger](https://api.sitelink.topcon.com/swagger/) page. Security tokens are provided to Sitelink3D v2 via the Authorization header parameter.
```

2021-12-10 05:15 UTC, Ryan-A-B commented on security/security_overview.md
> +Already we have presented enough information to make some sense of the Sitelink3D v2 REST API defined on our [Swagger](https://api.sitelink.topcon.com/swagger/) page. Security tokens are provided to
We should update swagger to drop X-Topcon-Auth

2021-12-10 05:15 UTC, Ryan-A-B commented on security/security_overview.md
> +    }
different tab sizes

2021-12-10 05:15 UTC, Ryan-A-B commented on security/security_overview.md
> +Let's add a modified subject and collectively define a exactly what the client_manager service can do to all clients within Loans Are Us. This provides a complete picture of what this permission is s
Might want to re-frame this slightly to be actions the bearer of the token can expect a service to perform on their behalf. The service can do what ever it likes to the resources under its control

2021-12-10 05:15 UTC, Ryan-A-B commented on security/security_overview.md
> +Armed with these new definitions, we are able to express the Loans Are Us Node policy described above as the following policy comprised of two permissions. The first permission states that the Node i
```suggestion
Armed with these new definitions, we are able to express the Loans Are Us Node policy described above as the following policy comprised of two permissions. The first permission states that the Node is free to chain any number of resource identifier strings to the subject that represents its own resource space and generate JWTs for any services and actions to operate on that space. The second is the permission delegated by Giant Bank that allows for JWTs to be created that control access to the subset of Giant Bank's resource space as defined by the B2B relationship between the banks.
```

2021-12-10 05:15 UTC, Ryan-A-B commented on security/security_overview.md
> +  "act": &nbsp;{
```suggestion
  "act": {
```

2021-12-10 05:15 UTC, Ryan-A-B commented on security/security_overview.md
> +```
```suggestion
```json
```

2021-12-10 05:15 UTC, Ryan-A-B commented on security/security_overview.md
> +  "act": &nbsp;{
```suggestion
  "act": {
```

2021-12-10 05:15 UTC, Ryan-A-B commented on services/README.md
> +Don’t let the terminology put you off. RDM is simply the technology we’ve built for defining and distributing objects within the Sitelink3D v2 ecosystem. RDM is one of the simplest ways to get workin
```suggestion
Don’t let the terminology put you off. RDM is simply the technology we’ve built for defining and distributing objects within the Sitelink3D v2 ecosystem. RDM is one of the simplest ways to get working with our API. In this chapter we’ll be looking at examples of creating objects by writing to the ```rdm``` microservice and then using views to query the data.
```

2021-12-10 05:16 UTC, Ryan-A-B commented on security/security_overview.md
> +```
we should do this for all code sections

2021-12-13 05:57 UTC, yeleva commented on security/security_overview.md
> +Let's add a modified subject and collectively define a exactly what the client_manager service can do to all clients within Loans Are Us. This provides a complete picture of what this permission is s
Agreed.

2021-12-13 05:58 UTC, yeleva commented on security/security_overview.md
> +```
Done.

2022-02-16 06:00 UTC, topcon-kduong commented on setup/getting_authorized_and_connected_to_api.md
> +Post https://{host}/token?code={}&grant_type=authorization_code&code_verifier={}
Quote URL in block

2022-02-16 06:05 UTC, topcon-kduong commented on setup/getting_authorized_and_connected_to_api.md
> +```
```suggestion
```json
```

2022-02-16 06:15 UTC, topcon-kduong commented on setup/getting_authorized_and_connected_to_api.md
> +e.g. scope=123456789abcdefghi12345678912
```suggestion
e.g. ```scope=123456789abcdefghi12345678912```
```

2022-02-16 06:18 UTC, topcon-kduong commented on setup/getting_authorized_and_connected_to_api.md
> +Post https://{host}/token?code={}&grant_type=authorization_code&code_verifier={}
Quote may look better

2022-02-16 06:28 UTC, topcon-kduong requested changes

2022-02-16 06:28 UTC, topcon-kduong commented on setup/getting_authorized_and_connected_to_api.md
> +https://{host}/authorize?client_id={}&redirect_uri={}&response_type=code&state={}&code_challenge={}&code_challenge_method=s256
```suggestion
```https://{host}/authorize?client_id={}&redirect_uri={}&response_type=code&state={}&code_challenge={}&code_challenge_method=s256```
```

2022-02-16 06:28 UTC, topcon-kduong commented on setup/getting_authorized_and_connected_to_api.md
> +| Authorization | Basic base64({client_id}:{client_secret}) |
```suggestion
| Authorization | Basic base64(```{client_id}```:```{client_secret}```) |
```

2022-02-16 06:28 UTC, topcon-kduong commented on setup/getting_authorized_and_connected_to_api.md
> +| Authorization | Basic base64({client_id}:{client_secret}) |
```suggestion
| Authorization | Basic base64(```{client_id}```:```{client_secret}```) |
```

2022-02-16 06:28 UTC, topcon-kduong commented on setup/getting_authorized_and_connected_to_api.md
> +POST https://{host}/token?refresh_token={}&grant_type=refresh_token
```suggestion
```POST https://{host}/token?refresh_token={}&grant_type=refresh_token```
```

2022-02-16 06:28 UTC, topcon-kduong commented on setup/getting_authorized_and_connected_to_api.md
> +The POST result contains the Access Token ("access_token") that can be used to authenticate Sitelink3D v2 API requests.
```suggestion
The POST result contains the Access Token ```"access_token"``` that can be used to authenticate Sitelink3D v2 API requests.
```

2022-02-17 00:42 UTC, yeleva commented on setup/getting_authorized_and_connected_to_api.md
> +```
Done.

2022-02-17 01:35 UTC, merged